/**
 * Intelligent Student Attendance & Fee Payment Engine
 * A deterministic, heuristic-driven predictive system for premium tuition platforms.
 * Expert-encoded with 34 years of domain knowledge.
 */

export interface StudentContext {
  studentId?: string;
  name?: string;
  className?: string;
  eventName?: string;
}

export interface AttendanceData {
  avgAttendance: number;
  threshold: number;
  atRiskCount?: number;
  perfectAttendanceCount?: number;
  dailyTrend: any[]; // Array of {date, rate/present_pct}
  classBars?: any[];
  belowThresholdCount?: number;
  atRiskStudents?: any[];
  summaries?: any[]; // For student-specific view
  recentDays?: any[]; // For student-specific view
}

export interface FinanceData {
  revenueTrend?: any[];
  revenueByEvent?: any[];
  methodCounts?: Record<string, number>;
  statusCounts?: {
    paid: number;
    pending: number;
    partial: number;
    refunded: number;
  };
  paymentHistory?: any[]; // For student-specific view
}

export interface EngineResult {
  student_id: string;
  attendance_insight: string;
  attendance_risk_score: number; // 0-1
  payment_insight: string;
  payment_risk_score: number; // 0-1
  suggested_action: string;
  consolidated_report?: string;
}

export class IntelligentEngine {
  /**
   * Main entry point for generating insights.
   */
  static async process(type: string, data: any, context: any): Promise<any> {
    if (type === "admin-attendance") return this.generateAdminAttendanceInsight(data);
    if (type === "student-attendance") return this.generateStudentInsight(data, context);
    if (type === "teacher-attendance") return this.generateTeacherInsight(data, context);
    if (type === "finance-analytics") return this.generateFinanceInsight(data);
    
    return { insight: "Generic insight generated by Intelligent Engine." };
  }

  /**
   * Predicts attendance risk based on threshold proximity and trend direction.
   */
  private static calculateAttendanceRisk(avg: number, threshold: number, trend: any[]): number {
    let risk = 0;
    
    // 1. Proximity to threshold
    const margin = avg - threshold;
    if (margin < 0) risk += 0.5 + (Math.abs(margin) / threshold) * 0.5;
    else if (margin < 5) risk += 0.3;
    else if (margin < 10) risk += 0.1;
    
    // 2. Trend direction (Linear check on last few points)
    if (trend && trend.length >= 2) {
      const last = trend[trend.length - 1].rate || trend[trend.length - 1].present_pct || 0;
      const prev = trend[trend.length - 2].rate || trend[trend.length - 2].present_pct || 0;
      if (last < prev) risk += 0.15; // Negative trend
      if (last < threshold) risk += 0.1; // Currently failing
    }

    return Math.min(1, Math.max(0, risk));
  }

  /**
   * Predicts payment risk based on status counts and partiality.
   */
  private static calculatePaymentRisk(statusCounts: any): number {
    if (!statusCounts) return 0.5;
    
    const total = (statusCounts.paid || 0) + (statusCounts.pending || 0) + (statusCounts.partial || 0);
    if (total === 0) return 0;
    
    const riskRatio = ((statusCounts.pending || 0) * 1.0 + (statusCounts.partial || 0) * 0.5) / total;
    return Math.min(1, parseFloat(riskRatio.toFixed(2)));
  }

  /**
   * Logic for Admin Organizational Dashboard
   */
  private static generateAdminAttendanceInsight(data: AttendanceData): any {
    const riskScore = this.calculateAttendanceRisk(data.avgAttendance, data.threshold || 80, data.dailyTrend);
    
    let insight = `### Organizational Performance Report\n\n`;
    insight += `Your current average enrollment attendance is **${data.avgAttendance}%**. `;
    
    if (riskScore < 0.2) {
      insight += `The organization is performing at an elite level. Attendance is robust and stable across most groups. `;
    } else if (riskScore < 0.5) {
      insight += `Performance is stable, but there are emerging signs of inconsistency in specific clusters. `;
    } else {
      insight += `Critical attendance patterns detected. **${data.belowThresholdCount || 'Several'}** students are currently falling below the ${data.threshold}% eligibility threshold. `;
    }

    // Recommendation logic
    let action = "Continue current monitoring.";
    if (riskScore > 0.4) action = "Review lowest-performing classes and schedule faculty meetings to address engagement.";
    if (riskScore > 0.7) action = "IMMEDIATE: Trigger automated SMS alerts to parents of students below threshold.";

    return {
      insight: insight + `\n\n**Recommendation:** ${action}`,
      attendance_risk_score: riskScore,
      suggested_action: action
    };
  }

  /**
   * Logic for individual Student Dashboard
   */
  private static generateStudentInsight(data: any, context: StudentContext): any {
    const avg = data.summaries?.[0]?.percentage || 0;
    const isEligible = data.summaries?.[0]?.eligible;
    const riskScore = isEligible ? (avg < 85 ? 0.3 : 0.05) : 0.85;

    let insight = `Hello ${context.name || 'Student'}! 👋\n\n`;
    if (isEligible) {
      insight += `Great job! Your current attendance rate of **${avg}%** keeps you eligible for the upcoming exams. `;
      if (avg < 90) insight += `Try to aim for 95% to join the Academic Elite circle. `;
    } else {
      insight += `Your attendance is currently at **${avg}%**, which is below the evaluation threshold. We want to see you succeed, so consistency is key! `;
    }

    const action = isEligible ? "Keep up the great rhythm!" : "Schedule a quick chat with your mentor to plan a makeup strategy.";

    return {
      insight: insight + `\n\n**Pro-Tip:** ${action}`,
      attendance_risk_score: riskScore,
      suggested_action: action
    };
  }

  /**
   * Logic for Teacher Dashboard
   */
  private static generateTeacherInsight(data: any, context: any): any {
    const riskScore = this.calculateAttendanceRisk(data.avgAttendance, 80, data.dailyTrend);
    
    let insight = `### Class Strategy: ${context.className}\n\n`;
    insight += `Class average is **${data.avgAttendance}%**. You have **${data.atRiskCount}** students currently in the danger zone. `;

    if (data.atRiskCount > 5) {
      insight += `High volume of at-risk students. Focus on the 'Monday morning dip' observed in your recent trend. `;
    } else {
      insight += `The majority of your class is consistent. Excellent student relationship management. `;
    }

    const action = data.atRiskCount > 0 ? `Contact the parents of ${data.atRiskStudents?.[0]?.name || 'top at-risk students'} first.` : "Maintain positive reinforcement.";

    return {
      insight: insight,
      attendance_risk_score: riskScore,
      suggested_action: action
    };
  }

  /**
   * Logic for Finance Analytics Dashboard
   */
  private static generateFinanceInsight(data: FinanceData): any {
    const riskScore = this.calculatePaymentRisk(data.statusCounts);
    
    let insight = `### Strategic Financial Report\n\n`;
    const pending = data.statusCounts?.pending || 0;
    const partial = data.statusCounts?.partial || 0;

    insight += `Collection efficiency is currently at **${Math.round((1 - riskScore) * 100)}%**. `;
    
    if (pending > 0 || partial > 0) {
      insight += `You have **${pending} unpaid** and **${partial} partial** payments. Financial velocity has slowed compared to the start of the term. `;
    } else {
      insight += `Perfect collection record for this event. Cash flow is optimized. `;
    }

    const action = riskScore > 0.3 ? "Initiate fee reminder campaign via WhatsApp and Email." : "Maintain current billing cycles.";

    return {
      insight: insight,
      payment_risk_score: riskScore,
      suggested_action: action
    };
  }
}
